on:
  youtube:
    channel_id:
      - UCVkbqgnJ4VkhDIuzlcM_Icw
    playlist_id:
      - PLZ7pfAnYMac3_vclXkGDPXMWu551_Pglp
    config:
      active: false
jobs:
  send2webex:
    name: 'Perform REST API'
    runs-on: ubuntu-latest
    steps:
      - name: Sende Beschreibung
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.BD_GPAM_IT_INTERN_WEBEX_WEBHOOK_URL }}
          body: '{"markdown": "<b>${{on.youtube.outputs.title}}</b><br><br>${{on.youtube.outputs.description}}<br><br>${{on.youtube.outputs.link}}"}'
      - name: Sende Link
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.BD_GPAM_IT_INTERN_WEBEX_WEBHOOK_URL }}
          body: '{"text": "${{on.youtube.outputs.link}}"}'
